### ISSUE TITLE
PA2 - Phase I

### ISSUE THREAD

**Issue by AndroidBiscuit** [AndroidBiscuit/COMP-346#17]
### Behavior
Phase I will synchronize the access to the critical section for updating the accounts.

### TODO
 - [ ] Adapt the Java code provided to your solution of PA1 
 - [ ] Implement a second server thread in the main() method by respecting the changes already made in the constructor of the Server class. Consequently you need to modify the run() method of the Server class to accommodate the two threads and also to display the running time of each thread. The server can disconnect only when both threads have terminated
 - [ ] execute the program with DEBUG flags and notice the accounts with inconsistent results as shown in the file os-pa2-outputunsynchronized.txt. The accounts 60520, 22310 and 91715 should be inconsistent but that may sometimes change depending on the sequence of execution. I have forced inconsistency by sleeping for 100 ms a thread accessing the critical section in the deposit() method of the Server class
 - [ ] using synchronized methods or synchronized statements, protect properly the critical section of the methods deposit(), withdraw() and query(). Execute the program again and there should be no inconsistent results
 - [ ] Explain your choice of using either synchronized methods or synchronized statements
