### ISSUE TITLE
PA2 - Phase II

### ISSUE THREAD

**Issue by AndroidBiscuit** [AndroidBiscuit/COMP-346#18]
### Behavior
Phase II will coordinate the threads when accessing a full or an empty network buffer.

### TODO
 - [ ] The network buffers (i.e. inComingPacket, outGoingPacket) are synchronized using busy-waiting by constantly yielding the CPU until an empty buffer or a full buffer is available. This is good for the performance of the thread as it can respond quickly to the event but it is not good for the overall system performance as useful CPU cycles are wasted. 
 - [ ] Using the methods acquire() (similar to wait() or P()) and release() (similar to signal() or V()) of the class Semaphore, synchronize the operations of the network input buffers. The semaphores must be implemented in the methods send(), receive(), transferrIn() and transferOut() of the class Network. Sample output for this phase is in the file os-pa2-output-semaphores.txt
 - [ ] Execute the program and comment about the running times of the server threads compared to using busy-waiting in phase (i). 
 - [ ] Next, implement a third server thread and comment about the running times compared to the implementation with 2 threads
