### ISSUE TITLE
PA3 - Discuss task with teammate

### ISSUE THREAD

**Issue by AndroidBiscuit** [AndroidBiscuit/COMP-346#26]
###  Topics
- [x] Dining Philosophers problem

### Important 
- [x] Make sure it is correct, deadlock- and starvation-free implementation that uses Java’s synchronization primitives, such as wait() and notifyAll(); 
- [x] No use of Semaphore objects is allowed.
- [x] A philosopher is allowed to pickup the chopsticks if they are both available. That implies having states of each philosopher as presented in your book. You might want to consider the order in which to pick the chopsticks up.
- [x] If a given philosopher has decided to make a statement, they can only do so if no one else is talking at the moment. The philosopher wishing to make the statement has to wait in that case.

### TODO Methods
- [x] eat()
- [x] think()
- [x] talk()
- [x] run()
- [x] pickUp()
- [x] putDown()
- [x] requestTalk()
- [x] endTalk()

### Required files
- [x] common/BaseThread.java - unchanged
- [x] DiningPhilosophers.java - the main()
- [x] Philosopher.java - extends from BaseThread
- [x] Monitor.java - the monitor for the system
- [x] Makefile - take a look
