### ISSUE TITLE
PA3 - Tests

### ISSUE THREAD

**Issue by AndroidBiscuit** [AndroidBiscuit/COMP-346#32]
### TODO
Produce .txt files for the tests for tasks #29 and #30 and a couple of tests with chosen numbers

### Required documents
 - [x] Console output .txt file: decimal
 - [x] Console output .txt file: negative number
 - [x] Console output .txt file: zero
 - [x] Console output .txt file: no input
 - [x] Console output .txt file: other invalid input
 - [x] Console output .txt file: a couple of output files with chosen number of philosophers

**Comment by AndroidBiscuit** [comment]
Test files successfully made. Tested PA3 with inputs 1, 2, 20 and 100. Test results are in the "Test results folder"
